#!/usr/bin/env bash

set -euxo pipefail

mkdir -p ~/.local/bin

export PLATFORM=$(uname -s)

if [ "$PLATFORM" = Linux ]; then
   sudo apt-get update
   sudo apt-get install -y tig ripgrep pandoc
   # sudo apt-get install -y stow golang python3-pip python3.10-venv ranger
   # curl -fsSL https://deb.nodesource.com/setup_21.x | sudo -E bash - &&\
   #     sudo apt-get install -y nodejs

   mkdir --parent ~/.fonts
   for font in JetBrainsMono.tar.xz Go-Mono.tar.xz ; do
       if [ ! -f ~/.fonts/"${font}" ]; then
           curl -L -o ~/.fonts/"${font}" \
               https://github.com/ryanoasis/nerd-fonts/releases/download/v3.5.1/"${font}"
           tar xvf ~/.fonts/"${font}" -C ~/.fonts/
           sudo fc-cache -fv
       fi
   done
elif [ "$PLATFORM" = Darwin ]; then
    brew install stow
    # brew install golang node python3
    # pip3 install virtualenv
    brew install font-hack-nerd-font tig ripgrep pandoc
fi

echo "Fetch all git submodules..."
git submodule update --recursive --init

# Clean up old conf if there is any
rm -rf ~/.fzf
cp -r submodules/fzf ~/.fzf
~/.fzf/install --all

rm -rf ~/.vim ~/.config/kitty ~/.config/lazygit
rm -f ~/.tmux.conf

# Install diff tools
# install ydiff
curl -L https://raw.github.com/ymattw/ydiff/master/ydiff.py > ~/.local/bin/ydiff
chmod +x ~/.local/bin/ydiff
# install diff-so-fancy
curl -L https://github.com/so-fancy/diff-so-fancy/releases/latest/download/diff-so-fancy > ~/.local/bin/diff-so-fancy
chmod +x ~/.local/bin/diff-so-fancy

stow --target=$HOME vim nvim tmux ranger wezterm vscode kitty lazygit ghostty emacs herdr
git/configure-gitconfig.sh ${1:-}
